### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by Kilash2020** [mhvis/solar#15]
Hi,

I am getting this error message: 

AttributeError: module 'socket' has no attribute 'MSG_DONTWAIT'

Any idea what might be causing this error?

Thanks

**Comment by mhvis** [comment]
Could it be that you are trying to run the script on Windows? Windows is not supported, this script is only tested with Linux/POSIX.

**Comment by Kilash2020** [comment]
Yes that would be the issue, thanks

**Comment by mhvis** [comment]
I should've put this in the README, I have updated it now. Thanks for confirming.
